# Eigenschaften von Hunderassen

In [1]:
# Imports
import pandas as pd

# Einlesen der csv-Datei
df = pd.read_csv('./dog_breed_characteristics.csv')

# Beispielhafte Anzeige des Datensatzes
df.head()

,BreedName,AltBreedName,Group1,Group2,MaleWtKg,Temperment,AvgPupPrice,Intelligence,Watchdog,MalaysiaGuardedDog,MalaysiaProhibitedDog,MalaysiaPopularity,PopularityUS2017
0,Affenpinscher,NaN,Toy,Companion,4.0,"Active, Adventurous, Curious, Fun-loving, Play...",1000.0,37.0,1.0,NaN,NaN,NaN,147.0
1,Afghan Hound,NaN,Sporting,Sight,28.0,"Aloof, Clownish, Dignified, Happy, Independent",2250.0,79.0,1.0,NaN,NaN,NaN,93.0
2,African Hunting Dog,NaN,NaN,NaN,23.0,Wild,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Airedale Terrier,Airedale,Terrier,Terrier,26.0,"Alert, Confident, Courageous, Friendly, Intell...",700.0,29.0,4.0,NaN,NaN,NaN,55.0
4,Akbash,NaN,Working,Guardian,53.0,"Affectionate, Alert, Courageous, Independent, ...",600.0,NaN,5.0,NaN,NaN,NaN,NaN

In [2]:
# Speichern des Datensatzes als json-Datei
df.to_json('./dog_breed_characteristics.json', orient='index')